### ISSUE TITLE
Adda a newbe user manual

### ISSUE THREAD

**Issue by iw2evk** [phmarek/hantek-dso2000#1]
Hi,

I don't understand where are the requisite for use this scripts with my hantek dso2d15 scope.
seem they are not files to download for my linux lubuntu 20.04  or nothing to install like script or other files..
Can you make a step by step installation guide and user for beginners ?

Thanks
Roberto

**Comment by phmarek** [comment]
You'll need `python3` and the `python3-pyvisa` library - so while 20.04 is quite old, https://packages.ubuntu.com/search?keywords=python3-pyvisa says that a package is available; I believe `json` and `struct` are included in the default python installation.

So `sudo apt-get install python3-pyvisa` should be enough to get the script working.

**Comment by iw2evk** [comment]
No, seem it's not enought
i've ask on terminal:
dso-via-scpi list    
retourn:
dso-via-scpi: command not found

**Comment by phmarek** [comment]
Well, yeah, that's a feature of your UNIX shell.

Please try
```
./dso-via-scpi list
```
to tell your shell where to find the program.

For some background information, see eg. https://cets.seas.upenn.edu/answers/dot-path.html

**Comment by iw2evk** [comment]
iw2evk@iw2evk-4236j25:/src$ ./dso-via-scpi.py list
('USB0::1183::20574::CN2328029050857::0::INSTR',)
ok, recognized..note : i  most use .py after filename for working 

Now try some command

iw2evk@iw2evk-4236j25:/src$ ./dso-via-scpi.py
Traceback (most recent call last):          
  File "./dso-via-scpi.py", line 367, in <module>
    saveWave(filename)
  File "./dso-via-scpi.py", line 272, in saveWave
    wave = readWaveform(o)
  File "./dso-via-scpi.py", line 226, in readWaveform
    'trigger_time': float(trigger_time),
ValueError: could not convert string to float: b'5+0.00e+0'

another command..

iw2evk@iw2evk-4236j25:/src$ ./dso-via-scpi.py save waveform foobar.csv
Traceback (most recent call last):
  File "./dso-via-scpi.py", line 367, in <module>
    saveWave(filename)
  File "./dso-via-scpi.py", line 270, in saveWave
    output = io.open(filename, 'wt') if filename else sys.stdout
PermissionError: [Errno 13] Permission denied: 'foobar.csv'


what wrong ?
Many thanks

**Comment by phmarek** [comment]
```
ValueError: could not convert string to float: b'5+0.00e+0'
```
That one seems like the DSO returns the data in a different format than expected - it seems to be shifted by a byte.
Please look up the firmware and hardware version/revision.

```
PermissionError: [Errno 13] Permission denied: 'foobar.csv'
```
You're in a `/src` directory, does that have write permissions for your user and/or group?

**Comment by iw2evk** [comment]
![IMG_20240108_201307_429](https://github.com/phmarek/hantek-dso2000/assets/13957956/b28dc542-9836-495c-818d-4457502ff216)
[dso3kb_20230327-1.zip](https://github.com/phmarek/hantek-dso2000/files/13998735/dso3kb_20230327-1.zip)
Hi,

they are my system info's for oscilloscope in attachment


for my groups :

iw2evk@iw2evk-4236j25:~$ groups
iw2evk adm tty lp dialout cdrom sudo dip plugdev lpadmin sambashare usbusers

For user write /read permession : i've permission for read/write

P.s. for the next release can you add a Texual user interface for semplify the use and installation step -by-step instrucion?

Thanks

Roberto iw2evk
